import { getPinOffsets, parseSpiceValue, pinId } from "./eda-document";
import type { CircuitDocument, SchematicPart, WireConnection } from "./eda-types";

/** Union-find over pin references to collapse wired pins into electrical nets. */
export function buildNetMap(document: CircuitDocument) {
  const parent = new Map<string, string>();
  const rootOf = (value: string): string => {
    const parentValue = parent.get(value);
    if (!parentValue || parentValue === value) return value;
    const root = rootOf(parentValue);
    parent.set(value, root);
    return root;
  };
  const join = (a: string, b: string) => {
    if (!parent.has(a) || !parent.has(b)) return;
    const first = rootOf(a);
    const second = rootOf(b);
    if (first !== second) parent.set(second, first);
  };
  for (const part of document.parts) {
    getPinOffsets(part.type).forEach((_, pin) => parent.set(`${part.id}:${pin}`, `${part.id}:${pin}`));
  }
  for (const wire of document.connections) join(pinId(wire.from), pinId(wire.to));
  const grounds = document.parts.filter((part) => part.type === "ground");
  grounds.slice(1).forEach((ground) => join(`${grounds[0].id}:0`, `${ground.id}:0`));
  const groundRoot = grounds.length ? rootOf(`${grounds[0].id}:0`) : null;
  const names = new Map<string, string>();
  let counter = 1;
  const nodeName = (root: string) => {
    if (groundRoot && root === groundRoot) return "0";
    if (!names.has(root)) names.set(root, `N${String(counter++).padStart(3, "0")}`);
    return names.get(root) ?? "0";
  };
  return { rootOf, nodeName, groundRoot, netCount: names.size + (groundRoot ? 1 : 0) };
}

function spiceValueOf(value: string) {
  return value.trim().replace(/µ/g, "u").replace(/[ΩΩ]/g, "").replace(/\s+/g, "");
}

export function generateNetlist(document: CircuitDocument): string {
  const nets = buildNetMap(document);
  const nodeOf = (part: SchematicPart, pin: number) => nets.nodeName(nets.rootOf(`${part.id}:${pin}`));
  const lines: string[] = [
    `* ${document.name || "Circuit Studio design"}`,
    `* Generated by Circuit Studio · ${new Date().toISOString()}`,
    "* Modified Nodal Analysis · transient · AC · DC",
    ".option TEMP=27",
  ];
  const potWipers: SchematicPart[] = [];
  const coupled: { first: SchematicPart; second: SchematicPart; k: number }[] = [];

  for (const part of document.parts) {
    if (part.type === "ground") continue;
    const pins = getPinOffsets(part.type).map((_, pin) => nodeOf(part, pin));
    const a = pins[0] ?? "0";
    const b = pins[1] ?? "0";
    const value = spiceValueOf(part.value);
    switch (part.type) {
      case "resistor":
      case "thermistor":
        lines.push(`${part.ref} ${a} ${b} ${value}${part.tolerance ? ` TC=${part.tempCoeff ?? "0"}` : ""}`);
        break;
      case "capacitor":
        lines.push(`${part.ref} ${a} ${b} ${value} IC=0`);
        break;
      case "inductor":
        lines.push(`${part.ref} ${a} ${b} ${value}`);
        break;
      case "voltage":
        lines.push(`${part.ref} ${a} ${b} DC ${value.replace(/^DC/i, "")}`);
        break;
      case "ac-source":
      case "pulse-source":
      case "function-generator":
        lines.push(`${part.ref} ${a} ${b} ${value}`);
        break;
      case "current":
        lines.push(`${part.ref} ${a} ${b} DC ${value.replace(/^DC/i, "")}`);
        break;
      case "diode":
      case "led":
      case "zener":
      case "schottky":
        lines.push(`${part.ref} ${a} ${b} ${part.model ?? "DDEFAULT"}`);
        break;
      case "transistor-npn":
      case "transistor-pnp":
        lines.push(`${part.ref} ${pins[1] ?? "0"} ${pins[0] ?? "0"} ${pins[2] ?? "0"} ${part.model ?? "QN3904"}`);
        break;
      case "mosfet-n":
      case "mosfet-p":
        lines.push(`${part.ref} ${pins[1] ?? "0"} ${pins[0] ?? "0"} ${pins[2] ?? "0"} ${part.model ?? "M2N7000"}`);
        break;
      case "potentiometer":
        potWipers.push(part);
        break;
      case "transformer":
        coupled.push({ first: part, second: part, k: 0.99 });
        lines.push(`${part.ref}a ${pins[0]} ${pins[1]} ${value.split(":")[0] ?? "1m"}`);
        lines.push(`${part.ref}b ${pins[2]} ${pins[3]} ${value.split(":")[1] ?? "1m"}`);
        break;
      case "vcvs":
        lines.push(`E${part.ref.replace(/[^0-9A-Za-z]/g, "")} ${a} ${b} ${pins[2]} ${pins[3]} ${value}`);
        break;
      case "vccs":
        lines.push(`G${part.ref.replace(/[^0-9A-Za-z]/g, "")} ${a} ${b} ${pins[2]} ${pins[3]} ${value}`);
        break;
      case "ccvs":
        lines.push(`H${part.ref.replace(/[^0-9A-Za-z]/g, "")} ${a} ${b} ${pins[2]} ${pins[3]} ${value}`);
        break;
      case "cccs":
        lines.push(`F${part.ref.replace(/[^0-9A-Za-z]/g, "")} ${a} ${b} ${pins[2]} ${pins[3]} ${value}`);
        break;
      case "switch":
        lines.push(`${part.ref} ${a} ${b} ${part.closed ? "0.01" : "1e9"}`);
        break;
      case "lamp":
      case "buzzer":
      case "motor":
      case "relay":
        lines.push(`${part.ref} ${a} ${b} ${value}`);
        break;
      case "timer":
        lines.push(`* ${part.ref} ${part.model ?? "NE555"} — behavioural model`);
        break;
      case "logic":
      case "microcontroller":
      case "seven-segment":
        lines.push(`* ${part.ref} ${part.value} — digital model`);
        break;
      default:
        lines.push(`* ${part.ref} ${part.value} (${part.type})`);
    }
  }

  for (const pot of potWipers) {
    const total = Math.max(parseSpiceValue(pot.value, 10_000), 1);
    const position = Math.min(1, Math.max(0, pot.position ?? 0.5));
    lines.push(`${pot.ref}a ${nodeOf(pot, 0)} ${nodeOf(pot, 1)} ${(total * position).toPrecision(4)}`);
    lines.push(`${partSuffix(pot)}b ${nodeOf(pot, 1)} ${nodeOf(pot, 2)} ${(total * (1 - position)).toPrecision(4)}`);
  }
  for (const entry of coupled) {
    lines.push(`K${entry.first.ref.replace(/[^0-9A-Za-z]/g, "")} ${entry.first.ref}a ${entry.first.ref}b ${entry.k}`);
  }

  lines.push("", ".model DDDEFAULT D(IS=2.52n N=1.75 RS=0.568)", ".model QN3904 NPN(IS=6.734f BF=416.4 NF=1.259 VAF=74.03)", ".model M2N7000 NMOS(KP=0.16 VTO=2.5)", ".tran 10u 8m", ".ac dec 100 10 100k", ".op", ".end");
  return lines.join("\n");
}

function partSuffix(part: SchematicPart) {
  return part.ref;
}

export function parseSpiceDocument(text: string, name: string): CircuitDocument | null {
  const parsed: { ref: string; type: string; nodes: string[]; value: string }[] = [];
  const typeByPrefix: Record<string, string> = {
    R: "resistor", C: "capacitor", L: "inductor", V: "voltage", I: "current",
    D: "diode", Q: "transistor-npn", E: "vcvs", G: "vccs", H: "ccvs", F: "cccs",
  };
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("*") || line.startsWith(".") || line.startsWith("+")) continue;
    const tokens = line.split(/\s+/);
    const ref = tokens[0];
    const type = typeByPrefix[ref?.[0]?.toUpperCase() ?? ""];
    if (!type || tokens.length < 3) continue;
    parsed.push({ ref, type, nodes: tokens.slice(1, 3), value: tokens.slice(3).join(" ").replace(/^DC\s+/i, "") });
  }
  if (!parsed.length) return null;

  const parts: SchematicPart[] = [];
  const connections: WireConnection[] = [];
  const nodePins = new Map<string, { partId: string; pin: number }[]>();
  const columns = 4;
  parsed.forEach((item, index) => {
    const id = `import-${index + 1}`;
    const position = { x: 300 + (index % columns) * 200, y: 230 + Math.floor(index / columns) * 120 };
    parts.push({ id, type: item.type, ref: item.ref, value: item.value, ...position, rotation: 0 });
    item.nodes.forEach((net, pin) => {
      const references = nodePins.get(net) ?? [];
      references.push({ partId: id, pin });
      nodePins.set(net, references);
    });
  });

  let groundIndex = 0;
  for (const [net, pins] of nodePins.entries()) {
    const references = [...pins];
    if (net === "0" || net.toLowerCase() === "gnd") {
      const groundId = `import-gnd-${groundIndex++}`;
      parts.push({ id: groundId, type: "ground", ref: "GND", value: "0", x: 300 + groundIndex * 200, y: 660, rotation: 0 });
      references.push({ partId: groundId, pin: 0 });
    }
    for (let index = 1; index < references.length; index += 1) {
      const from = references[0];
      const to = references[index];
      connections.push({ id: `import-w-${connections.length + 1}`, from, to });
    }
  }

  const output = parts.find((part) => part.type === "resistor") ?? parts[0];
  return {
    version: 1,
    name,
    parts,
    connections,
    probes: output ? [{ id: "import-probe", name: "V(out)", pin: { partId: output.id, pin: 1 } }] : [],
  };
}
